import Footer from "./components/Footer";
import Header from "./components/Navbar"; // Ensure correct import
import "./globals.css";

export const metadata = {
  title: "Futnext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
